apiVersion: v1
kind: Secret
metadata:
  name: ticketflow-secrets
  namespace: ticketflow
type: Opaque
stringData:
  POSTGRES_USER: ticketflow
  POSTGRES_PASSWORD: ticketflow_pass
  POSTGRES_DB: ticketflow
  DATABASE_URL: postgresql://ticketflow:ticketflow_pass@postgres:5432/ticketflow
